# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Tale
paginate:       5
baseurl:        "/"
url:            "https://nareshbab.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Naresh Kumar
  url:          http://nareshbab.github.io
  email:        naresh_kumar_2016@cba.isb.edu

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/nareshbab/nareshbab.github.io

# Gems
plugins:
  - jekyll-paginate
